/* File generated by the BNF Converter (bnfc 2.9.5). */

/* C Abstract Syntax Implementation. */

#include <stdio.h>
#include <stdlib.h>
#include "Absyn.h"

/********************   StartInput    ********************/

Input make_StartInput(ListJob p1)
{
    Input tmp = (Input) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating StartInput!\n");
        exit(1);
    }
    tmp->kind = is_StartInput;
    tmp->u.startinput_.listjob_ = p1;
    return tmp;
}

/********************   OneJobFG    ********************/

Job make_OneJobFG(Condition p1)
{
    Job tmp = (Job) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating OneJobFG!\n");
        exit(1);
    }
    tmp->kind = is_OneJobFG;
    tmp->u.onejobfg_.condition_ = p1;
    return tmp;
}

/********************   OneJobBG    ********************/

Job make_OneJobBG(Condition p1)
{
    Job tmp = (Job) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating OneJobBG!\n");
        exit(1);
    }
    tmp->kind = is_OneJobBG;
    tmp->u.onejobbg_.condition_ = p1;
    return tmp;
}

/********************   AssignJob    ********************/

Job make_AssignJob(Assign p1)
{
    Job tmp = (Job) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating AssignJob!\n");
        exit(1);
    }
    tmp->kind = is_AssignJob;
    tmp->u.assignjob_.assign_ = p1;
    return tmp;
}

/********************   IfStmt    ********************/

Job make_IfStmt(Condition p1, ListJob p2, OptElse p3)
{
    Job tmp = (Job) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating IfStmt!\n");
        exit(1);
    }
    tmp->kind = is_IfStmt;
    tmp->u.ifstmt_.condition_ = p1;
    tmp->u.ifstmt_.listjob_ = p2;
    tmp->u.ifstmt_.optelse_ = p3;
    return tmp;
}

/********************   ListJob    ********************/

ListJob make_ListJob(Job p1, ListJob p2)
{
    ListJob tmp = (ListJob) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListJob!\n");
        exit(1);
    }
    tmp->job_ = p1;
    tmp->listjob_ = p2;
    return tmp;
}

/********************   NoElse    ********************/

OptElse make_NoElse()
{
    OptElse tmp = (OptElse) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating NoElse!\n");
        exit(1);
    }
    tmp->kind = is_NoElse;
    return tmp;
}

/********************   ElsePart    ********************/

OptElse make_ElsePart(ListJob p1)
{
    OptElse tmp = (OptElse) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ElsePart!\n");
        exit(1);
    }
    tmp->kind = is_ElsePart;
    tmp->u.elsepart_.listjob_ = p1;
    return tmp;
}

/********************   ElifPart    ********************/

OptElse make_ElifPart(Condition p1, ListJob p2, OptElse p3)
{
    OptElse tmp = (OptElse) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ElifPart!\n");
        exit(1);
    }
    tmp->kind = is_ElifPart;
    tmp->u.elifpart_.condition_ = p1;
    tmp->u.elifpart_.listjob_ = p2;
    tmp->u.elifpart_.optelse_ = p3;
    return tmp;
}

/********************   CondSingle    ********************/

Condition make_CondSingle(NegCmd p1)
{
    Condition tmp = (Condition) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CondSingle!\n");
        exit(1);
    }
    tmp->kind = is_CondSingle;
    tmp->u.condsingle_.negcmd_ = p1;
    return tmp;
}

/********************   CondAnd    ********************/

Condition make_CondAnd(NegCmd p1, Condition p2)
{
    Condition tmp = (Condition) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CondAnd!\n");
        exit(1);
    }
    tmp->kind = is_CondAnd;
    tmp->u.condand_.negcmd_ = p1;
    tmp->u.condand_.condition_ = p2;
    return tmp;
}

/********************   CondOr    ********************/

Condition make_CondOr(NegCmd p1, Condition p2)
{
    Condition tmp = (Condition) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CondOr!\n");
        exit(1);
    }
    tmp->kind = is_CondOr;
    tmp->u.condor_.negcmd_ = p1;
    tmp->u.condor_.condition_ = p2;
    return tmp;
}

/********************   PlainCL    ********************/

NegCmd make_PlainCL(CommandLine p1)
{
    NegCmd tmp = (NegCmd) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating PlainCL!\n");
        exit(1);
    }
    tmp->kind = is_PlainCL;
    tmp->u.plaincl_.commandline_ = p1;
    return tmp;
}

/********************   NotCL    ********************/

NegCmd make_NotCL(NegCmd p1)
{
    NegCmd tmp = (NegCmd) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating NotCL!\n");
        exit(1);
    }
    tmp->kind = is_NotCL;
    tmp->u.notcl_.negcmd_ = p1;
    return tmp;
}

/********************   TimeCmd    ********************/

NegCmd make_TimeCmd(NegCmd p1)
{
    NegCmd tmp = (NegCmd) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TimeCmd!\n");
        exit(1);
    }
    tmp->kind = is_TimeCmd;
    tmp->u.timecmd_.negcmd_ = p1;
    return tmp;
}

/********************   Subshell    ********************/

NegCmd make_Subshell(ListJob p1)
{
    NegCmd tmp = (NegCmd) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Subshell!\n");
        exit(1);
    }
    tmp->kind = is_Subshell;
    tmp->u.subshell_.listjob_ = p1;
    return tmp;
}

/********************   Group    ********************/

NegCmd make_Group(ListJob p1)
{
    NegCmd tmp = (NegCmd) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Group!\n");
        exit(1);
    }
    tmp->kind = is_Group;
    tmp->u.group_.listjob_ = p1;
    return tmp;
}

/********************   MkCmdLine    ********************/

CommandLine make_MkCmdLine(Pipeline p1, OptRedir p2)
{
    CommandLine tmp = (CommandLine) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating MkCmdLine!\n");
        exit(1);
    }
    tmp->kind = is_MkCmdLine;
    tmp->u.mkcmdline_.pipeline_ = p1;
    tmp->u.mkcmdline_.optredir_ = p2;
    return tmp;
}

/********************   NoRedir    ********************/

OptRedir make_NoRedir()
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating NoRedir!\n");
        exit(1);
    }
    tmp->kind = is_NoRedir;
    return tmp;
}

/********************   ErrAppRedir    ********************/

OptRedir make_ErrAppRedir(Word p1)
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ErrAppRedir!\n");
        exit(1);
    }
    tmp->kind = is_ErrAppRedir;
    tmp->u.errappredir_.word_ = p1;
    return tmp;
}

/********************   ErrRedir    ********************/

OptRedir make_ErrRedir(Word p1)
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ErrRedir!\n");
        exit(1);
    }
    tmp->kind = is_ErrRedir;
    tmp->u.errredir_.word_ = p1;
    return tmp;
}

/********************   BothRedir    ********************/

OptRedir make_BothRedir(Word p1)
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating BothRedir!\n");
        exit(1);
    }
    tmp->kind = is_BothRedir;
    tmp->u.bothredir_.word_ = p1;
    return tmp;
}

/********************   AppendRedir    ********************/

OptRedir make_AppendRedir(Word p1)
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating AppendRedir!\n");
        exit(1);
    }
    tmp->kind = is_AppendRedir;
    tmp->u.appendredir_.word_ = p1;
    return tmp;
}

/********************   OutRedir    ********************/

OptRedir make_OutRedir(Word p1)
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating OutRedir!\n");
        exit(1);
    }
    tmp->kind = is_OutRedir;
    tmp->u.outredir_.word_ = p1;
    return tmp;
}

/********************   InRedir    ********************/

OptRedir make_InRedir(Word p1)
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating InRedir!\n");
        exit(1);
    }
    tmp->kind = is_InRedir;
    tmp->u.inredir_.word_ = p1;
    return tmp;
}

/********************   InOutRedir    ********************/

OptRedir make_InOutRedir(Word p1, Word p2)
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating InOutRedir!\n");
        exit(1);
    }
    tmp->kind = is_InOutRedir;
    tmp->u.inoutredir_.word_1 = p1;
    tmp->u.inoutredir_.word_2 = p2;
    return tmp;
}

/********************   OutInRedir    ********************/

OptRedir make_OutInRedir(Word p1, Word p2)
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating OutInRedir!\n");
        exit(1);
    }
    tmp->kind = is_OutInRedir;
    tmp->u.outinredir_.word_1 = p1;
    tmp->u.outinredir_.word_2 = p2;
    return tmp;
}

/********************   Single    ********************/

Pipeline make_Single(CommandPart p1)
{
    Pipeline tmp = (Pipeline) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Single!\n");
        exit(1);
    }
    tmp->kind = is_Single;
    tmp->u.single_.commandpart_ = p1;
    return tmp;
}

/********************   Pipe    ********************/

Pipeline make_Pipe(CommandPart p1, Pipeline p2)
{
    Pipeline tmp = (Pipeline) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Pipe!\n");
        exit(1);
    }
    tmp->kind = is_Pipe;
    tmp->u.pipe_.commandpart_ = p1;
    tmp->u.pipe_.pipeline_ = p2;
    return tmp;
}

/********************   Cmd    ********************/

CommandPart make_Cmd(Word p1, ListWord p2)
{
    CommandPart tmp = (CommandPart) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Cmd!\n");
        exit(1);
    }
    tmp->kind = is_Cmd;
    tmp->u.cmd_.word_ = p1;
    tmp->u.cmd_.listword_ = p2;
    return tmp;
}

/********************   ListWord    ********************/

ListWord make_ListWord(Word p1, ListWord p2)
{
    ListWord tmp = (ListWord) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListWord!\n");
        exit(1);
    }
    tmp->word_ = p1;
    tmp->listword_ = p2;
    return tmp;
}

/***************************   Cloning   ******************************/

Input clone_Input(Input p)
{
  switch(p->kind)
  {
  case is_StartInput:
    return make_StartInput (clone_ListJob(p->u.startinput_.listjob_));

  default:
    fprintf(stderr, "Error: bad kind field when cloning Input!\n");
    exit(1);
  }
}

Job clone_Job(Job p)
{
  switch(p->kind)
  {
  case is_OneJobFG:
    return make_OneJobFG (clone_Condition(p->u.onejobfg_.condition_));

  case is_OneJobBG:
    return make_OneJobBG (clone_Condition(p->u.onejobbg_.condition_));

  case is_AssignJob:
    return make_AssignJob (strdup(p->u.assignjob_.assign_));

  case is_IfStmt:
    return make_IfStmt
      ( clone_Condition(p->u.ifstmt_.condition_)
      , clone_ListJob(p->u.ifstmt_.listjob_)
      , clone_OptElse(p->u.ifstmt_.optelse_)
      );

  default:
    fprintf(stderr, "Error: bad kind field when cloning Job!\n");
    exit(1);
  }
}

ListJob clone_ListJob(ListJob listjob)
{
  if (listjob)
  {
    /* clone of non-empty list */
    return make_ListJob
      ( clone_Job(listjob->job_)
      , clone_ListJob(listjob->listjob_)
      );
  }
  else return NULL; /* clone of empty list */
}

OptElse clone_OptElse(OptElse p)
{
  switch(p->kind)
  {
  case is_NoElse:
    return make_NoElse ();

  case is_ElsePart:
    return make_ElsePart (clone_ListJob(p->u.elsepart_.listjob_));

  case is_ElifPart:
    return make_ElifPart
      ( clone_Condition(p->u.elifpart_.condition_)
      , clone_ListJob(p->u.elifpart_.listjob_)
      , clone_OptElse(p->u.elifpart_.optelse_)
      );

  default:
    fprintf(stderr, "Error: bad kind field when cloning OptElse!\n");
    exit(1);
  }
}

Condition clone_Condition(Condition p)
{
  switch(p->kind)
  {
  case is_CondSingle:
    return make_CondSingle (clone_NegCmd(p->u.condsingle_.negcmd_));

  case is_CondAnd:
    return make_CondAnd
      ( clone_NegCmd(p->u.condand_.negcmd_)
      , clone_Condition(p->u.condand_.condition_)
      );

  case is_CondOr:
    return make_CondOr
      ( clone_NegCmd(p->u.condor_.negcmd_)
      , clone_Condition(p->u.condor_.condition_)
      );

  default:
    fprintf(stderr, "Error: bad kind field when cloning Condition!\n");
    exit(1);
  }
}

NegCmd clone_NegCmd(NegCmd p)
{
  switch(p->kind)
  {
  case is_PlainCL:
    return make_PlainCL (clone_CommandLine(p->u.plaincl_.commandline_));

  case is_NotCL:
    return make_NotCL (clone_NegCmd(p->u.notcl_.negcmd_));

  case is_TimeCmd:
    return make_TimeCmd (clone_NegCmd(p->u.timecmd_.negcmd_));

  case is_Subshell:
    return make_Subshell (clone_ListJob(p->u.subshell_.listjob_));

  case is_Group:
    return make_Group (clone_ListJob(p->u.group_.listjob_));

  default:
    fprintf(stderr, "Error: bad kind field when cloning NegCmd!\n");
    exit(1);
  }
}

CommandLine clone_CommandLine(CommandLine p)
{
  switch(p->kind)
  {
  case is_MkCmdLine:
    return make_MkCmdLine
      ( clone_Pipeline(p->u.mkcmdline_.pipeline_)
      , clone_OptRedir(p->u.mkcmdline_.optredir_)
      );

  default:
    fprintf(stderr, "Error: bad kind field when cloning CommandLine!\n");
    exit(1);
  }
}

OptRedir clone_OptRedir(OptRedir p)
{
  switch(p->kind)
  {
  case is_NoRedir:
    return make_NoRedir ();

  case is_ErrAppRedir:
    return make_ErrAppRedir (strdup(p->u.errappredir_.word_));

  case is_ErrRedir:
    return make_ErrRedir (strdup(p->u.errredir_.word_));

  case is_BothRedir:
    return make_BothRedir (strdup(p->u.bothredir_.word_));

  case is_AppendRedir:
    return make_AppendRedir (strdup(p->u.appendredir_.word_));

  case is_OutRedir:
    return make_OutRedir (strdup(p->u.outredir_.word_));

  case is_InRedir:
    return make_InRedir (strdup(p->u.inredir_.word_));

  case is_InOutRedir:
    return make_InOutRedir
      ( strdup(p->u.inoutredir_.word_1)
      , strdup(p->u.inoutredir_.word_2)
      );

  case is_OutInRedir:
    return make_OutInRedir
      ( strdup(p->u.outinredir_.word_1)
      , strdup(p->u.outinredir_.word_2)
      );

  default:
    fprintf(stderr, "Error: bad kind field when cloning OptRedir!\n");
    exit(1);
  }
}

Pipeline clone_Pipeline(Pipeline p)
{
  switch(p->kind)
  {
  case is_Single:
    return make_Single (clone_CommandPart(p->u.single_.commandpart_));

  case is_Pipe:
    return make_Pipe
      ( clone_CommandPart(p->u.pipe_.commandpart_)
      , clone_Pipeline(p->u.pipe_.pipeline_)
      );

  default:
    fprintf(stderr, "Error: bad kind field when cloning Pipeline!\n");
    exit(1);
  }
}

CommandPart clone_CommandPart(CommandPart p)
{
  switch(p->kind)
  {
  case is_Cmd:
    return make_Cmd
      ( strdup(p->u.cmd_.word_)
      , clone_ListWord(p->u.cmd_.listword_)
      );

  default:
    fprintf(stderr, "Error: bad kind field when cloning CommandPart!\n");
    exit(1);
  }
}

ListWord clone_ListWord(ListWord listword)
{
  if (listword)
  {
    /* clone of non-empty list */
    return make_ListWord
      ( strdup(listword->word_)
      , clone_ListWord(listword->listword_)
      );
  }
  else return NULL; /* clone of empty list */
}

/********************   Recursive Destructors    **********************/

/* These free an entire abstract syntax tree
 * including all subtrees and strings.
 *
 * Will not work properly if there is sharing in the tree,
 * i.e., when some pointers are aliased.  In this case
 * it will attempt to free the same memory twice.
 */

void free_Input(Input p)
{
  switch(p->kind)
  {
  case is_StartInput:
    free_ListJob(p->u.startinput_.listjob_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing Input!\n");
    exit(1);
  }
  free(p);
}

void free_Job(Job p)
{
  switch(p->kind)
  {
  case is_OneJobFG:
    free_Condition(p->u.onejobfg_.condition_);
    break;

  case is_OneJobBG:
    free_Condition(p->u.onejobbg_.condition_);
    break;

  case is_AssignJob:
    free(p->u.assignjob_.assign_);
    break;

  case is_IfStmt:
    free_Condition(p->u.ifstmt_.condition_);
    free_ListJob(p->u.ifstmt_.listjob_);
    free_OptElse(p->u.ifstmt_.optelse_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing Job!\n");
    exit(1);
  }
  free(p);
}

void free_ListJob(ListJob listjob)
{
  if (listjob)
  {
    free_Job(listjob->job_);
    free_ListJob(listjob->listjob_);
    free(listjob);
  }
}

void free_OptElse(OptElse p)
{
  switch(p->kind)
  {
  case is_NoElse:
    break;

  case is_ElsePart:
    free_ListJob(p->u.elsepart_.listjob_);
    break;

  case is_ElifPart:
    free_Condition(p->u.elifpart_.condition_);
    free_ListJob(p->u.elifpart_.listjob_);
    free_OptElse(p->u.elifpart_.optelse_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing OptElse!\n");
    exit(1);
  }
  free(p);
}

void free_Condition(Condition p)
{
  switch(p->kind)
  {
  case is_CondSingle:
    free_NegCmd(p->u.condsingle_.negcmd_);
    break;

  case is_CondAnd:
    free_NegCmd(p->u.condand_.negcmd_);
    free_Condition(p->u.condand_.condition_);
    break;

  case is_CondOr:
    free_NegCmd(p->u.condor_.negcmd_);
    free_Condition(p->u.condor_.condition_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing Condition!\n");
    exit(1);
  }
  free(p);
}

void free_NegCmd(NegCmd p)
{
  switch(p->kind)
  {
  case is_PlainCL:
    free_CommandLine(p->u.plaincl_.commandline_);
    break;

  case is_NotCL:
    free_NegCmd(p->u.notcl_.negcmd_);
    break;

  case is_TimeCmd:
    free_NegCmd(p->u.timecmd_.negcmd_);
    break;

  case is_Subshell:
    free_ListJob(p->u.subshell_.listjob_);
    break;

  case is_Group:
    free_ListJob(p->u.group_.listjob_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing NegCmd!\n");
    exit(1);
  }
  free(p);
}

void free_CommandLine(CommandLine p)
{
  switch(p->kind)
  {
  case is_MkCmdLine:
    free_Pipeline(p->u.mkcmdline_.pipeline_);
    free_OptRedir(p->u.mkcmdline_.optredir_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing CommandLine!\n");
    exit(1);
  }
  free(p);
}

void free_OptRedir(OptRedir p)
{
  switch(p->kind)
  {
  case is_NoRedir:
    break;

  case is_ErrAppRedir:
    free(p->u.errappredir_.word_);
    break;

  case is_ErrRedir:
    free(p->u.errredir_.word_);
    break;

  case is_BothRedir:
    free(p->u.bothredir_.word_);
    break;

  case is_AppendRedir:
    free(p->u.appendredir_.word_);
    break;

  case is_OutRedir:
    free(p->u.outredir_.word_);
    break;

  case is_InRedir:
    free(p->u.inredir_.word_);
    break;

  case is_InOutRedir:
    free(p->u.inoutredir_.word_1);
    free(p->u.inoutredir_.word_2);
    break;

  case is_OutInRedir:
    free(p->u.outinredir_.word_1);
    free(p->u.outinredir_.word_2);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing OptRedir!\n");
    exit(1);
  }
  free(p);
}

void free_Pipeline(Pipeline p)
{
  switch(p->kind)
  {
  case is_Single:
    free_CommandPart(p->u.single_.commandpart_);
    break;

  case is_Pipe:
    free_CommandPart(p->u.pipe_.commandpart_);
    free_Pipeline(p->u.pipe_.pipeline_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing Pipeline!\n");
    exit(1);
  }
  free(p);
}

void free_CommandPart(CommandPart p)
{
  switch(p->kind)
  {
  case is_Cmd:
    free(p->u.cmd_.word_);
    free_ListWord(p->u.cmd_.listword_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing CommandPart!\n");
    exit(1);
  }
  free(p);
}

void free_ListWord(ListWord listword)
{
  if (listword)
  {
    free(listword->word_);
    free_ListWord(listword->listword_);
    free(listword);
  }
}

