/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef ABSYN_HEADER
#define ABSYN_HEADER

/* strdup was not in the ISO C standard before 6/2019 (C2x), but in POSIX 1003.1.
 * See: https://en.cppreference.com/w/c/experimental/dynamic/strdup
 * Setting _POSIX_C_SOURCE to 200809L activates strdup in string.h.
 */
#define _POSIX_C_SOURCE 200809L

#include <stddef.h>  /* NULL */
#include <string.h>  /* strdup */

/* C++ Abstract Syntax Interface.*/

/********************   TypeDef Section    ********************/

typedef int Integer;
typedef char Char;
typedef double Double;
typedef char* String;
typedef char* Ident;
typedef char* Word;
typedef char* Assign;

/********************   Forward Declarations    ***********************/
struct Input_;
typedef struct Input_ *Input;

struct Job_;
typedef struct Job_ *Job;

struct ListJob_;
typedef struct ListJob_ *ListJob;

struct OptElse_;
typedef struct OptElse_ *OptElse;

struct Condition_;
typedef struct Condition_ *Condition;

struct NegCmd_;
typedef struct NegCmd_ *NegCmd;

struct CommandLine_;
typedef struct CommandLine_ *CommandLine;

struct OptRedir_;
typedef struct OptRedir_ *OptRedir;

struct Pipeline_;
typedef struct Pipeline_ *Pipeline;

struct CommandPart_;
typedef struct CommandPart_ *CommandPart;

struct ListWord_;
typedef struct ListWord_ *ListWord;

/********************   Abstract Syntax Classes    ********************/

struct Input_
{
  enum { is_StartInput } kind;
  union
  {
    struct { ListJob listjob_; } startinput_;
  } u;
};

Input make_StartInput(ListJob p0);

struct Job_
{
  enum { is_OneJobFG, is_OneJobBG, is_AssignJob, is_IfStmt } kind;
  union
  {
    struct { Condition condition_; } onejobfg_;
    struct { Condition condition_; } onejobbg_;
    struct { Assign assign_; } assignjob_;
    struct { Condition condition_; ListJob listjob_; OptElse optelse_; } ifstmt_;
  } u;
};

Job make_OneJobFG(Condition p0);
Job make_OneJobBG(Condition p0);
Job make_AssignJob(Assign p0);
Job make_IfStmt(Condition p0, ListJob p1, OptElse p2);

struct ListJob_
{
  Job job_;
  ListJob listjob_;
};

ListJob make_ListJob(Job p1, ListJob p2);

struct OptElse_
{
  enum { is_NoElse, is_ElsePart, is_ElifPart } kind;
  union
  {
    struct { ListJob listjob_; } elsepart_;
    struct { Condition condition_; ListJob listjob_; OptElse optelse_; } elifpart_;
  } u;
};

OptElse make_NoElse(void);
OptElse make_ElsePart(ListJob p0);
OptElse make_ElifPart(Condition p0, ListJob p1, OptElse p2);

struct Condition_
{
  enum { is_CondSingle, is_CondAnd, is_CondOr } kind;
  union
  {
    struct { NegCmd negcmd_; } condsingle_;
    struct { Condition condition_; NegCmd negcmd_; } condand_;
    struct { Condition condition_; NegCmd negcmd_; } condor_;
  } u;
};

Condition make_CondSingle(NegCmd p0);
Condition make_CondAnd(NegCmd p0, Condition p1);
Condition make_CondOr(NegCmd p0, Condition p1);

struct NegCmd_
{
  enum { is_PlainCL, is_NotCL, is_TimeCmd, is_Subshell, is_Group } kind;
  union
  {
    struct { CommandLine commandline_; } plaincl_;
    struct { NegCmd negcmd_; } notcl_;
    struct { NegCmd negcmd_; } timecmd_;
    struct { ListJob listjob_; } subshell_;
    struct { ListJob listjob_; } group_;
  } u;
};

NegCmd make_PlainCL(CommandLine p0);
NegCmd make_NotCL(NegCmd p0);
NegCmd make_TimeCmd(NegCmd p0);
NegCmd make_Subshell(ListJob p0);
NegCmd make_Group(ListJob p0);

struct CommandLine_
{
  enum { is_MkCmdLine } kind;
  union
  {
    struct { OptRedir optredir_; Pipeline pipeline_; } mkcmdline_;
  } u;
};

CommandLine make_MkCmdLine(Pipeline p0, OptRedir p1);

struct OptRedir_
{
  enum { is_NoRedir, is_AppendRedir, is_OutRedir, is_InRedir, is_InOutRedir, is_OutInRedir } kind;
  union
  {
    struct { Word word_; } appendredir_;
    struct { Word word_; } outredir_;
    struct { Word word_; } inredir_;
    struct { Word word_1, word_2; } inoutredir_;
    struct { Word word_1, word_2; } outinredir_;
  } u;
};

OptRedir make_NoRedir(void);
OptRedir make_AppendRedir(Word p0);
OptRedir make_OutRedir(Word p0);
OptRedir make_InRedir(Word p0);
OptRedir make_InOutRedir(Word p0, Word p1);
OptRedir make_OutInRedir(Word p0, Word p1);

struct Pipeline_
{
  enum { is_Single, is_Pipe } kind;
  union
  {
    struct { CommandPart commandpart_; } single_;
    struct { CommandPart commandpart_; Pipeline pipeline_; } pipe_;
  } u;
};

Pipeline make_Single(CommandPart p0);
Pipeline make_Pipe(CommandPart p0, Pipeline p1);

struct CommandPart_
{
  enum { is_Cmd } kind;
  union
  {
    struct { ListWord listword_; Word word_; } cmd_;
  } u;
};

CommandPart make_Cmd(Word p0, ListWord p1);

struct ListWord_
{
  Word word_;
  ListWord listword_;
};

ListWord make_ListWord(Word p1, ListWord p2);

/***************************   Cloning   ******************************/

Input clone_Input(Input p);
Job clone_Job(Job p);
ListJob clone_ListJob(ListJob p);
OptElse clone_OptElse(OptElse p);
Condition clone_Condition(Condition p);
NegCmd clone_NegCmd(NegCmd p);
CommandLine clone_CommandLine(CommandLine p);
OptRedir clone_OptRedir(OptRedir p);
Pipeline clone_Pipeline(Pipeline p);
CommandPart clone_CommandPart(CommandPart p);
ListWord clone_ListWord(ListWord p);

/********************   Recursive Destructors    **********************/

/* These free an entire abstract syntax tree
 * including all subtrees and strings.
 *
 * Will not work properly if there is sharing in the tree,
 * i.e., when some pointers are aliased.  In this case
 * it will attempt to free the same memory twice.
 */

void free_Input(Input p);
void free_Job(Job p);
void free_ListJob(ListJob p);
void free_OptElse(OptElse p);
void free_Condition(Condition p);
void free_NegCmd(NegCmd p);
void free_CommandLine(CommandLine p);
void free_OptRedir(OptRedir p);
void free_Pipeline(Pipeline p);
void free_CommandPart(CommandPart p);
void free_ListWord(ListWord p);


#endif
