/* -*- c -*- File generated by the BNF Converter (bnfc 2.9.5). */

/* Parser definition to be used with Bison. */

/* Generate header file for lexer. */
%defines "Bison.h"

/* Reentrant parser */
%pure_parser
  /* From Bison 2.3b (2008): %define api.pure full */
%lex-param   { yyscan_t scanner }
%parse-param { yyscan_t scanner }

/* Turn on line/column tracking in the grammar_lloc structure: */
%locations

/* Argument to the parser to be filled with the parsed tree. */
%parse-param { YYSTYPE *result }

%{
/* Begin C preamble code */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "Absyn.h"

#define YYMAXDEPTH 10000000

/* The type yyscan_t is defined by flex, but we need it in the parser already. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;
extern YY_BUFFER_STATE grammar__scan_string(const char *str, yyscan_t scanner);
extern void grammar__delete_buffer(YY_BUFFER_STATE buf, yyscan_t scanner);

extern void grammar_lex_destroy(yyscan_t scanner);
extern char* grammar_get_text(yyscan_t scanner);

extern yyscan_t grammar__initialize_lexer(FILE * inp);

/* List reversal functions. */
ListJob reverseListJob(ListJob l)
{
  ListJob prev = 0;
  ListJob tmp = 0;
  while (l)
  {
    tmp = l->listjob_;
    l->listjob_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListWord reverseListWord(ListWord l)
{
  ListWord prev = 0;
  ListWord tmp = 0;
  while (l)
  {
    tmp = l->listword_;
    l->listword_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}

/* End C preamble code */
%}

%union
{
  int    _int;
  char   _char;
  double _double;
  char*  _string;
  Input input_;
  Job job_;
  ListJob listjob_;
  OptElse optelse_;
  Condition condition_;
  NegCmd negcmd_;
  CommandLine commandline_;
  OptRedir optredir_;
  Pipeline pipeline_;
  CommandPart commandpart_;
  ListWord listword_;
}

%{
void yyerror(YYLTYPE *loc, yyscan_t scanner, YYSTYPE *result, const char *msg)
{
  fprintf(stderr, "error: %d,%d: %s at %s\n",
    loc->first_line, loc->first_column, msg, grammar_get_text(scanner));
}

int yyparse(yyscan_t scanner, YYSTYPE *result);

extern int yylex(YYSTYPE *lvalp, YYLTYPE *llocp, yyscan_t scanner);
%}

%token          _ERROR_
%token          _BANG     /* ! */
%token          _AMP      /* & */
%token          _DAMP     /* && */
%token          _SYMB_11  /* &> */
%token          _LPAREN   /* ( */
%token          _RPAREN   /* ) */
%token          _SYMB_10  /* 2> */
%token          _SYMB_9   /* 2>> */
%token          _SEMI     /* ; */
%token          _LT       /* < */
%token          _GT       /* > */
%token          _DGT      /* >> */
%token          _KW_elif  /* elif */
%token          _KW_else  /* else */
%token          _KW_fi    /* fi */
%token          _KW_if    /* if */
%token          _KW_then  /* then */
%token          _KW_time  /* time */
%token          _LBRACE   /* { */
%token          _BAR      /* | */
%token          _DBAR     /* || */
%token          _RBRACE   /* } */
%token<_string> T_Assign  /* Assign */
%token<_string> T_Word    /* Word */

%type <input_> Input
%type <job_> Job
%type <listjob_> ListJob
%type <optelse_> OptElse
%type <condition_> Condition
%type <negcmd_> NegCmd
%type <commandline_> CommandLine
%type <optredir_> OptRedir
%type <pipeline_> Pipeline
%type <commandpart_> CommandPart
%type <listword_> ListWord

%start Input

%%

Input : ListJob { $$ = make_StartInput($1); result->input_ = $$; }
;
Job : Condition { $$ = make_OneJobFG($1); }
  | Condition _AMP { $$ = make_OneJobBG($1); }
  | T_Assign { $$ = make_AssignJob($1); }
  | _KW_if Condition _KW_then ListJob OptElse _KW_fi { $$ = make_IfStmt($2, $4, $5); }
;
ListJob : Job { $$ = make_ListJob($1, 0); }
  | Job _SEMI ListJob { $$ = make_ListJob($1, $3); }
;
OptElse : /* empty */ { $$ = make_NoElse(); }
  | _KW_else ListJob { $$ = make_ElsePart($2); }
  | _KW_elif Condition _KW_then ListJob OptElse { $$ = make_ElifPart($2, $4, $5); }
;
Condition : NegCmd { $$ = make_CondSingle($1); }
  | NegCmd _DAMP Condition { $$ = make_CondAnd($1, $3); }
  | NegCmd _DBAR Condition { $$ = make_CondOr($1, $3); }
;
NegCmd : CommandLine { $$ = make_PlainCL($1); }
  | _BANG NegCmd { $$ = make_NotCL($2); }
  | _KW_time NegCmd { $$ = make_TimeCmd($2); }
  | _LPAREN ListJob _RPAREN { $$ = make_Subshell($2); }
  | _LBRACE ListJob _RBRACE { $$ = make_Group($2); }
;
CommandLine : Pipeline OptRedir { $$ = make_MkCmdLine($1, $2); }
;
OptRedir : /* empty */ { $$ = make_NoRedir(); }
  | _SYMB_9 T_Word { $$ = make_ErrAppRedir($2); }
  | _SYMB_10 T_Word { $$ = make_ErrRedir($2); }
  | _SYMB_11 T_Word { $$ = make_BothRedir($2); }
  | _DGT T_Word { $$ = make_AppendRedir($2); }
  | _GT T_Word { $$ = make_OutRedir($2); }
  | _LT T_Word { $$ = make_InRedir($2); }
  | _LT T_Word _GT T_Word { $$ = make_InOutRedir($2, $4); }
  | _GT T_Word _LT T_Word { $$ = make_OutInRedir($2, $4); }
;
Pipeline : CommandPart { $$ = make_Single($1); }
  | CommandPart _BAR Pipeline { $$ = make_Pipe($1, $3); }
;
CommandPart : T_Word ListWord { $$ = make_Cmd($1, $2); }
;
ListWord : /* empty */ { $$ = 0; }
  | T_Word ListWord { $$ = make_ListWord($1, $2); }
;

%%


/* Entrypoint: parse Input from file. */
Input pInput(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = grammar__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  grammar_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.input_;
  }
}

/* Entrypoint: parse Input from string. */
Input psInput(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = grammar__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = grammar__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  grammar__delete_buffer(buf, scanner);
  grammar_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.input_;
  }
}



