/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printInput(Input p)
{
  _n_ = 0;
  bufReset();
  ppInput(p, 0);
  return buf_;
}
char *showInput(Input p)
{
  _n_ = 0;
  bufReset();
  shInput(p);
  return buf_;
}
void ppInput(Input p, int _i_)
{
  switch(p->kind)
  {
  case is_StartInput:
    if (_i_ > 0) renderC(_L_PAREN);
    ppListJob(p->u.startinput_.listjob_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Input!\n");
    exit(1);
  }
}

void ppJob(Job p, int _i_)
{
  switch(p->kind)
  {
  case is_OneJobFG:
    if (_i_ > 0) renderC(_L_PAREN);
    ppCondition(p->u.onejobfg_.condition_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OneJobBG:
    if (_i_ > 0) renderC(_L_PAREN);
    ppCondition(p->u.onejobbg_.condition_, 0);
    renderC('&');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_AssignJob:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.assignjob_.assign_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_IfStmt:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("if");
    ppCondition(p->u.ifstmt_.condition_, 0);
    renderS("then");
    ppListJob(p->u.ifstmt_.listjob_, 0);
    ppOptElse(p->u.ifstmt_.optelse_, 0);
    renderS("fi");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ForStmt:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("for");
    ppIdent(p->u.forstmt_.word_, 0);
    renderS("in");
    ppListWord(p->u.forstmt_.listword_, 0);
    renderS("do");
    ppListJob(p->u.forstmt_.listjob_, 0);
    renderS("done");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_WhileStmt:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("while");
    ppCondition(p->u.whilestmt_.condition_, 0);
    renderS("do");
    ppListJob(p->u.whilestmt_.listjob_, 0);
    renderS("done");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_UntilStmt:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("until");
    ppCondition(p->u.untilstmt_.condition_, 0);
    renderS("do");
    ppListJob(p->u.untilstmt_.listjob_, 0);
    renderS("done");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_BreakStmt:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("break");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ContStmt:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("continue");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Job!\n");
    exit(1);
  }
}

void ppListJob(ListJob listjob, int i)
{
  if (listjob == 0)
  { /* nil */
  }
  else if (listjob->listjob_ == 0)
  { /* last */
    ppJob(listjob->job_, 0);
  }
  else
  { /* cons */
    ppJob(listjob->job_, 0);
    renderC(';');
    ppListJob(listjob->listjob_, 0);
  }
}

void ppOptElse(OptElse p, int _i_)
{
  switch(p->kind)
  {
  case is_NoElse:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ElsePart:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("else");
    ppListJob(p->u.elsepart_.listjob_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ElifPart:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("elif");
    ppCondition(p->u.elifpart_.condition_, 0);
    renderS("then");
    ppListJob(p->u.elifpart_.listjob_, 0);
    ppOptElse(p->u.elifpart_.optelse_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OptElse!\n");
    exit(1);
  }
}

void ppCondition(Condition p, int _i_)
{
  switch(p->kind)
  {
  case is_CondSingle:
    if (_i_ > 0) renderC(_L_PAREN);
    ppNegCmd(p->u.condsingle_.negcmd_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CondAnd:
    if (_i_ > 0) renderC(_L_PAREN);
    ppNegCmd(p->u.condand_.negcmd_, 0);
    renderS("&&");
    ppCondition(p->u.condand_.condition_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CondOr:
    if (_i_ > 0) renderC(_L_PAREN);
    ppNegCmd(p->u.condor_.negcmd_, 0);
    renderS("||");
    ppCondition(p->u.condor_.condition_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Condition!\n");
    exit(1);
  }
}

void ppNegCmd(NegCmd p, int _i_)
{
  switch(p->kind)
  {
  case is_PlainCL:
    if (_i_ > 0) renderC(_L_PAREN);
    ppCommandLine(p->u.plaincl_.commandline_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_NotCL:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('!');
    ppNegCmd(p->u.notcl_.negcmd_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_TimeCmd:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("time");
    ppNegCmd(p->u.timecmd_.negcmd_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Subshell:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('(');
    ppListJob(p->u.subshell_.listjob_, 0);
    renderC(')');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Group:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('{');
    ppListJob(p->u.group_.listjob_, 0);
    renderC('}');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing NegCmd!\n");
    exit(1);
  }
}

void ppCommandLine(CommandLine p, int _i_)
{
  switch(p->kind)
  {
  case is_MkCmdLine:
    if (_i_ > 0) renderC(_L_PAREN);
    ppPipeline(p->u.mkcmdline_.pipeline_, 0);
    ppOptRedir(p->u.mkcmdline_.optredir_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandLine!\n");
    exit(1);
  }
}

void ppOptRedir(OptRedir p, int _i_)
{
  switch(p->kind)
  {
  case is_NoRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ErrAppRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("2>>");
    ppIdent(p->u.errappredir_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ErrRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("2>");
    ppIdent(p->u.errredir_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_BothRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("&>");
    ppIdent(p->u.bothredir_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_AppendRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS(">>");
    ppIdent(p->u.appendredir_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OutRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('>');
    ppIdent(p->u.outredir_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_InRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    ppIdent(p->u.inredir_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_InOutRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    ppIdent(p->u.inoutredir_.word_1, 0);
    renderC('>');
    ppIdent(p->u.inoutredir_.word_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OutInRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('>');
    ppIdent(p->u.outinredir_.word_1, 0);
    renderC('<');
    ppIdent(p->u.outinredir_.word_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OptRedir!\n");
    exit(1);
  }
}

void ppPipeline(Pipeline p, int _i_)
{
  switch(p->kind)
  {
  case is_Single:
    if (_i_ > 0) renderC(_L_PAREN);
    ppCommandPart(p->u.single_.commandpart_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Pipe:
    if (_i_ > 0) renderC(_L_PAREN);
    ppCommandPart(p->u.pipe_.commandpart_, 0);
    renderC('|');
    ppPipeline(p->u.pipe_.pipeline_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Pipeline!\n");
    exit(1);
  }
}

void ppArg(Arg p, int _i_)
{
  switch(p->kind)
  {
  case is_WrdArg:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.wrdarg_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ArithArg:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.aritharg_.arithexp_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PSubstInArg:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.psubstinarg_.procsubstin_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PSubstOutArg:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.psubstoutarg_.procsubstout_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_AssignArg:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.assignarg_.assign_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Arg!\n");
    exit(1);
  }
}

void ppListArg(ListArg listarg, int i)
{
  if (listarg == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppArg(listarg->arg_, 0);
    renderC(' ');
    ppListArg(listarg->listarg_, 0);
  }
}

void ppCommandPart(CommandPart p, int _i_)
{
  switch(p->kind)
  {
  case is_Cmd:
    if (_i_ > 0) renderC(_L_PAREN);
    ppArg(p->u.cmd_.arg_, 0);
    ppListArg(p->u.cmd_.listarg_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandPart!\n");
    exit(1);
  }
}

void ppListWord(ListWord listword, int i)
{
  if (listword == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppIdent(listword->word_, 0);
    renderC(' ');
    ppListWord(listword->listword_, 0);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
  bufAppendC(' ');
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

void ppArithExp(String s, int i)
{
  renderS(s);
}


void ppProcSubstIn(String s, int i)
{
  renderS(s);
}


void ppProcSubstOut(String s, int i)
{
  renderS(s);
}


void ppAssign(String s, int i)
{
  renderS(s);
}


void ppWord(String s, int i)
{
  renderS(s);
}


void shInput(Input p)
{
  switch(p->kind)
  {
  case is_StartInput:
    bufAppendC('(');

    bufAppendS("StartInput");

    bufAppendC(' ');

    shListJob(p->u.startinput_.listjob_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Input!\n");
    exit(1);
  }
}

void shJob(Job p)
{
  switch(p->kind)
  {
  case is_OneJobFG:
    bufAppendC('(');

    bufAppendS("OneJobFG");

    bufAppendC(' ');

    shCondition(p->u.onejobfg_.condition_);

    bufAppendC(')');

    break;
  case is_OneJobBG:
    bufAppendC('(');

    bufAppendS("OneJobBG");

    bufAppendC(' ');

    shCondition(p->u.onejobbg_.condition_);

    bufAppendC(')');

    break;
  case is_AssignJob:
    bufAppendC('(');

    bufAppendS("AssignJob");

    bufAppendC(' ');

    shIdent(p->u.assignjob_.assign_);

    bufAppendC(')');

    break;
  case is_IfStmt:
    bufAppendC('(');

    bufAppendS("IfStmt");

    bufAppendC(' ');

    shCondition(p->u.ifstmt_.condition_);
  bufAppendC(' ');
    shListJob(p->u.ifstmt_.listjob_);
  bufAppendC(' ');
    shOptElse(p->u.ifstmt_.optelse_);

    bufAppendC(')');

    break;
  case is_ForStmt:
    bufAppendC('(');

    bufAppendS("ForStmt");

    bufAppendC(' ');

    shIdent(p->u.forstmt_.word_);
  bufAppendC(' ');
    shListWord(p->u.forstmt_.listword_);
  bufAppendC(' ');
    shListJob(p->u.forstmt_.listjob_);

    bufAppendC(')');

    break;
  case is_WhileStmt:
    bufAppendC('(');

    bufAppendS("WhileStmt");

    bufAppendC(' ');

    shCondition(p->u.whilestmt_.condition_);
  bufAppendC(' ');
    shListJob(p->u.whilestmt_.listjob_);

    bufAppendC(')');

    break;
  case is_UntilStmt:
    bufAppendC('(');

    bufAppendS("UntilStmt");

    bufAppendC(' ');

    shCondition(p->u.untilstmt_.condition_);
  bufAppendC(' ');
    shListJob(p->u.untilstmt_.listjob_);

    bufAppendC(')');

    break;
  case is_BreakStmt:

    bufAppendS("BreakStmt");




    break;
  case is_ContStmt:

    bufAppendS("ContStmt");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Job!\n");
    exit(1);
  }
}

void shListJob(ListJob listjob)
{
  bufAppendC('[');
  while(listjob != 0)
  {
    if (listjob->listjob_)
    {
      shJob(listjob->job_);
      bufAppendS(", ");
      listjob = listjob->listjob_;
    }
    else
    {
      shJob(listjob->job_);
      listjob = 0;
    }
  }
  bufAppendC(']');
}

void shOptElse(OptElse p)
{
  switch(p->kind)
  {
  case is_NoElse:

    bufAppendS("NoElse");




    break;
  case is_ElsePart:
    bufAppendC('(');

    bufAppendS("ElsePart");

    bufAppendC(' ');

    shListJob(p->u.elsepart_.listjob_);

    bufAppendC(')');

    break;
  case is_ElifPart:
    bufAppendC('(');

    bufAppendS("ElifPart");

    bufAppendC(' ');

    shCondition(p->u.elifpart_.condition_);
  bufAppendC(' ');
    shListJob(p->u.elifpart_.listjob_);
  bufAppendC(' ');
    shOptElse(p->u.elifpart_.optelse_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing OptElse!\n");
    exit(1);
  }
}

void shCondition(Condition p)
{
  switch(p->kind)
  {
  case is_CondSingle:
    bufAppendC('(');

    bufAppendS("CondSingle");

    bufAppendC(' ');

    shNegCmd(p->u.condsingle_.negcmd_);

    bufAppendC(')');

    break;
  case is_CondAnd:
    bufAppendC('(');

    bufAppendS("CondAnd");

    bufAppendC(' ');

    shNegCmd(p->u.condand_.negcmd_);
  bufAppendC(' ');
    shCondition(p->u.condand_.condition_);

    bufAppendC(')');

    break;
  case is_CondOr:
    bufAppendC('(');

    bufAppendS("CondOr");

    bufAppendC(' ');

    shNegCmd(p->u.condor_.negcmd_);
  bufAppendC(' ');
    shCondition(p->u.condor_.condition_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Condition!\n");
    exit(1);
  }
}

void shNegCmd(NegCmd p)
{
  switch(p->kind)
  {
  case is_PlainCL:
    bufAppendC('(');

    bufAppendS("PlainCL");

    bufAppendC(' ');

    shCommandLine(p->u.plaincl_.commandline_);

    bufAppendC(')');

    break;
  case is_NotCL:
    bufAppendC('(');

    bufAppendS("NotCL");

    bufAppendC(' ');

    shNegCmd(p->u.notcl_.negcmd_);

    bufAppendC(')');

    break;
  case is_TimeCmd:
    bufAppendC('(');

    bufAppendS("TimeCmd");

    bufAppendC(' ');

    shNegCmd(p->u.timecmd_.negcmd_);

    bufAppendC(')');

    break;
  case is_Subshell:
    bufAppendC('(');

    bufAppendS("Subshell");

    bufAppendC(' ');

    shListJob(p->u.subshell_.listjob_);

    bufAppendC(')');

    break;
  case is_Group:
    bufAppendC('(');

    bufAppendS("Group");

    bufAppendC(' ');

    shListJob(p->u.group_.listjob_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing NegCmd!\n");
    exit(1);
  }
}

void shCommandLine(CommandLine p)
{
  switch(p->kind)
  {
  case is_MkCmdLine:
    bufAppendC('(');

    bufAppendS("MkCmdLine");

    bufAppendC(' ');

    shPipeline(p->u.mkcmdline_.pipeline_);
  bufAppendC(' ');
    shOptRedir(p->u.mkcmdline_.optredir_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing CommandLine!\n");
    exit(1);
  }
}

void shOptRedir(OptRedir p)
{
  switch(p->kind)
  {
  case is_NoRedir:

    bufAppendS("NoRedir");




    break;
  case is_ErrAppRedir:
    bufAppendC('(');

    bufAppendS("ErrAppRedir");

    bufAppendC(' ');

    shIdent(p->u.errappredir_.word_);

    bufAppendC(')');

    break;
  case is_ErrRedir:
    bufAppendC('(');

    bufAppendS("ErrRedir");

    bufAppendC(' ');

    shIdent(p->u.errredir_.word_);

    bufAppendC(')');

    break;
  case is_BothRedir:
    bufAppendC('(');

    bufAppendS("BothRedir");

    bufAppendC(' ');

    shIdent(p->u.bothredir_.word_);

    bufAppendC(')');

    break;
  case is_AppendRedir:
    bufAppendC('(');

    bufAppendS("AppendRedir");

    bufAppendC(' ');

    shIdent(p->u.appendredir_.word_);

    bufAppendC(')');

    break;
  case is_OutRedir:
    bufAppendC('(');

    bufAppendS("OutRedir");

    bufAppendC(' ');

    shIdent(p->u.outredir_.word_);

    bufAppendC(')');

    break;
  case is_InRedir:
    bufAppendC('(');

    bufAppendS("InRedir");

    bufAppendC(' ');

    shIdent(p->u.inredir_.word_);

    bufAppendC(')');

    break;
  case is_InOutRedir:
    bufAppendC('(');

    bufAppendS("InOutRedir");

    bufAppendC(' ');

    shIdent(p->u.inoutredir_.word_1);
  bufAppendC(' ');
    shIdent(p->u.inoutredir_.word_2);

    bufAppendC(')');

    break;
  case is_OutInRedir:
    bufAppendC('(');

    bufAppendS("OutInRedir");

    bufAppendC(' ');

    shIdent(p->u.outinredir_.word_1);
  bufAppendC(' ');
    shIdent(p->u.outinredir_.word_2);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing OptRedir!\n");
    exit(1);
  }
}

void shPipeline(Pipeline p)
{
  switch(p->kind)
  {
  case is_Single:
    bufAppendC('(');

    bufAppendS("Single");

    bufAppendC(' ');

    shCommandPart(p->u.single_.commandpart_);

    bufAppendC(')');

    break;
  case is_Pipe:
    bufAppendC('(');

    bufAppendS("Pipe");

    bufAppendC(' ');

    shCommandPart(p->u.pipe_.commandpart_);
  bufAppendC(' ');
    shPipeline(p->u.pipe_.pipeline_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Pipeline!\n");
    exit(1);
  }
}

void shArg(Arg p)
{
  switch(p->kind)
  {
  case is_WrdArg:
    bufAppendC('(');

    bufAppendS("WrdArg");

    bufAppendC(' ');

    shIdent(p->u.wrdarg_.word_);

    bufAppendC(')');

    break;
  case is_ArithArg:
    bufAppendC('(');

    bufAppendS("ArithArg");

    bufAppendC(' ');

    shIdent(p->u.aritharg_.arithexp_);

    bufAppendC(')');

    break;
  case is_PSubstInArg:
    bufAppendC('(');

    bufAppendS("PSubstInArg");

    bufAppendC(' ');

    shIdent(p->u.psubstinarg_.procsubstin_);

    bufAppendC(')');

    break;
  case is_PSubstOutArg:
    bufAppendC('(');

    bufAppendS("PSubstOutArg");

    bufAppendC(' ');

    shIdent(p->u.psubstoutarg_.procsubstout_);

    bufAppendC(')');

    break;
  case is_AssignArg:
    bufAppendC('(');

    bufAppendS("AssignArg");

    bufAppendC(' ');

    shIdent(p->u.assignarg_.assign_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Arg!\n");
    exit(1);
  }
}

void shListArg(ListArg listarg)
{
  bufAppendC('[');
  while(listarg != 0)
  {
    if (listarg->listarg_)
    {
      shArg(listarg->arg_);
      bufAppendS(", ");
      listarg = listarg->listarg_;
    }
    else
    {
      shArg(listarg->arg_);
      listarg = 0;
    }
  }
  bufAppendC(']');
}

void shCommandPart(CommandPart p)
{
  switch(p->kind)
  {
  case is_Cmd:
    bufAppendC('(');

    bufAppendS("Cmd");

    bufAppendC(' ');

    shArg(p->u.cmd_.arg_);
  bufAppendC(' ');
    shListArg(p->u.cmd_.listarg_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing CommandPart!\n");
    exit(1);
  }
}

void shListWord(ListWord listword)
{
  bufAppendC('[');
  while(listword != 0)
  {
    if (listword->listword_)
    {
      shWord(listword->word_);
      bufAppendS(", ");
      listword = listword->listword_;
    }
    else
    {
      shWord(listword->word_);
      listword = 0;
    }
  }
  bufAppendC(']');
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void shArithExp(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}


void shProcSubstIn(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}


void shProcSubstOut(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}


void shAssign(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}


void shWord(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}


void bufEscapeS(const char *s)
{
  if (s) while (*s) bufEscapeC(*s++);
}
void bufEscapeC(const char c)
{
  switch(c)
  {
    case '\f': bufAppendS("\\f" ); break;
    case '\n': bufAppendS("\\n" ); break;
    case '\r': bufAppendS("\\r" ); break;
    case '\t': bufAppendS("\\t" ); break;
    case '\v': bufAppendS("\\v" ); break;
    case '\\': bufAppendS("\\\\"); break;
    case '\'': bufAppendS("\\'" ); break;
    case '\"': bufAppendS("\\\""); break;
    default: bufAppendC(c);
  }
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;

