/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef SKELETON_HEADER
#define SKELETON_HEADER
/* You might want to change the above name. */

#include "Absyn.h"


void visitInput(Input p);
void visitJob(Job p);
void visitListJob(ListJob p);
void visitOptElse(OptElse p);
void visitCondition(Condition p);
void visitNegCmd(NegCmd p);
void visitCommandLine(CommandLine p);
void visitOptRedir(OptRedir p);
void visitPipeline(Pipeline p);
void visitCommandPart(CommandPart p);
void visitListWord(ListWord p);

void visitWord(Word p);void visitAssign(Assign p);
void visitIdent(Ident i);
void visitInteger(Integer i);
void visitDouble(Double d);
void visitChar(Char c);
void visitString(String s);

#endif

