/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Visitor Traversal Skeleton. ***/
/* This traverses the abstract syntax tree.
   To use, copy Skeleton.h and Skeleton.c to
   new files. */

#include <stdlib.h>
#include <stdio.h>

#include "Skeleton.h"

void visitInput(Input p)
{
  switch(p->kind)
  {
  case is_StartInput:
    /* Code for StartInput Goes Here */
    visitListJob(p->u.startinput_.listjob_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Input!\n");
    exit(1);
  }
}

void visitJob(Job p)
{
  switch(p->kind)
  {
  case is_OneJobFG:
    /* Code for OneJobFG Goes Here */
    visitCondition(p->u.onejobfg_.condition_);
    break;
  case is_OneJobBG:
    /* Code for OneJobBG Goes Here */
    visitCondition(p->u.onejobbg_.condition_);
    break;
  case is_AssignJob:
    /* Code for AssignJob Goes Here */
    visitAssign(p->u.assignjob_.assign_);
    break;
  case is_IfStmt:
    /* Code for IfStmt Goes Here */
    visitCondition(p->u.ifstmt_.condition_);
    visitListJob(p->u.ifstmt_.listjob_);
    visitOptElse(p->u.ifstmt_.optelse_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Job!\n");
    exit(1);
  }
}

void visitListJob(ListJob listjob)
{
  while(listjob  != 0)
  {
    /* Code For ListJob Goes Here */
    visitJob(listjob->job_);
    listjob = listjob->listjob_;
  }
}

void visitOptElse(OptElse p)
{
  switch(p->kind)
  {
  case is_NoElse:
    /* Code for NoElse Goes Here */
    break;
  case is_ElsePart:
    /* Code for ElsePart Goes Here */
    visitListJob(p->u.elsepart_.listjob_);
    break;
  case is_ElifPart:
    /* Code for ElifPart Goes Here */
    visitCondition(p->u.elifpart_.condition_);
    visitListJob(p->u.elifpart_.listjob_);
    visitOptElse(p->u.elifpart_.optelse_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OptElse!\n");
    exit(1);
  }
}

void visitCondition(Condition p)
{
  switch(p->kind)
  {
  case is_CondSingle:
    /* Code for CondSingle Goes Here */
    visitNegCmd(p->u.condsingle_.negcmd_);
    break;
  case is_CondAnd:
    /* Code for CondAnd Goes Here */
    visitNegCmd(p->u.condand_.negcmd_);
    visitCondition(p->u.condand_.condition_);
    break;
  case is_CondOr:
    /* Code for CondOr Goes Here */
    visitNegCmd(p->u.condor_.negcmd_);
    visitCondition(p->u.condor_.condition_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Condition!\n");
    exit(1);
  }
}

void visitNegCmd(NegCmd p)
{
  switch(p->kind)
  {
  case is_PlainCL:
    /* Code for PlainCL Goes Here */
    visitCommandLine(p->u.plaincl_.commandline_);
    break;
  case is_NotCL:
    /* Code for NotCL Goes Here */
    visitNegCmd(p->u.notcl_.negcmd_);
    break;
  case is_TimeCmd:
    /* Code for TimeCmd Goes Here */
    visitNegCmd(p->u.timecmd_.negcmd_);
    break;
  case is_Subshell:
    /* Code for Subshell Goes Here */
    visitListJob(p->u.subshell_.listjob_);
    break;
  case is_Group:
    /* Code for Group Goes Here */
    visitListJob(p->u.group_.listjob_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing NegCmd!\n");
    exit(1);
  }
}

void visitCommandLine(CommandLine p)
{
  switch(p->kind)
  {
  case is_MkCmdLine:
    /* Code for MkCmdLine Goes Here */
    visitPipeline(p->u.mkcmdline_.pipeline_);
    visitOptRedir(p->u.mkcmdline_.optredir_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandLine!\n");
    exit(1);
  }
}

void visitOptRedir(OptRedir p)
{
  switch(p->kind)
  {
  case is_NoRedir:
    /* Code for NoRedir Goes Here */
    break;
  case is_ErrAppRedir:
    /* Code for ErrAppRedir Goes Here */
    visitWord(p->u.errappredir_.word_);
    break;
  case is_ErrRedir:
    /* Code for ErrRedir Goes Here */
    visitWord(p->u.errredir_.word_);
    break;
  case is_BothRedir:
    /* Code for BothRedir Goes Here */
    visitWord(p->u.bothredir_.word_);
    break;
  case is_AppendRedir:
    /* Code for AppendRedir Goes Here */
    visitWord(p->u.appendredir_.word_);
    break;
  case is_OutRedir:
    /* Code for OutRedir Goes Here */
    visitWord(p->u.outredir_.word_);
    break;
  case is_InRedir:
    /* Code for InRedir Goes Here */
    visitWord(p->u.inredir_.word_);
    break;
  case is_InOutRedir:
    /* Code for InOutRedir Goes Here */
    visitWord(p->u.inoutredir_.word_1);
    visitWord(p->u.inoutredir_.word_2);
    break;
  case is_OutInRedir:
    /* Code for OutInRedir Goes Here */
    visitWord(p->u.outinredir_.word_1);
    visitWord(p->u.outinredir_.word_2);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OptRedir!\n");
    exit(1);
  }
}

void visitPipeline(Pipeline p)
{
  switch(p->kind)
  {
  case is_Single:
    /* Code for Single Goes Here */
    visitCommandPart(p->u.single_.commandpart_);
    break;
  case is_Pipe:
    /* Code for Pipe Goes Here */
    visitCommandPart(p->u.pipe_.commandpart_);
    visitPipeline(p->u.pipe_.pipeline_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Pipeline!\n");
    exit(1);
  }
}

void visitCommandPart(CommandPart p)
{
  switch(p->kind)
  {
  case is_Cmd:
    /* Code for Cmd Goes Here */
    visitWord(p->u.cmd_.word_);
    visitListWord(p->u.cmd_.listword_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandPart!\n");
    exit(1);
  }
}

void visitListWord(ListWord listword)
{
  while(listword  != 0)
  {
    /* Code For ListWord Goes Here */
    visitWord(listword->word_);
    listword = listword->listword_;
  }
}

void visitWord(Word p)
{
  /* Code for Word Goes Here */
}
void visitAssign(Assign p)
{
  /* Code for Assign Goes Here */
}
void visitIdent(Ident i)
{
  /* Code for Ident Goes Here */
}
void visitInteger(Integer i)
{
  /* Code for Integer Goes Here */
}
void visitDouble(Double d)
{
  /* Code for Double Goes Here */
}
void visitChar(Char c)
{
  /* Code for Char Goes Here */
}
void visitString(String s)
{
  /* Code for String Goes Here */
}

